### PR TITLE
chore: update SIL logo for keymanweb.com

### PR DESCRIPTION
**Pull request by Meng-Heng**
Fixes: https://github.com/keymanapp/keyman.com/issues/460

image

### CODE REVIEW

**Comment by Meng-Heng** [comment]
I think this PR is waiting for #118.

**Comment by Meng-Heng** [comment]
I am unable to run keymanweb locally with bootstrap_version 0.10:
image
No build error:
image

**Comment by mcdurdin** [comment]
> I am unable to run keymanweb locally with bootstrap_version 0.10:

For this site, you need to use http://web.keyman.com.localhost rather than http://keymanweb.com.localhost, as we only bind to the web.keyman.com endpoint for test (for the live site, either web.keyman.com or keymanweb.com work)

**Comment by Meng-Heng** [comment]
I'm still seeing the same error.
image
image
image

**Comment by mcdurdin** [comment]
> I'm still seeing the same error.

Now it is a HTTP 500 error instead of a host-not-found error. HTTP 500 indicates something wrong in the backend. Should be able to check Docker logs to see what the error is.

**Comment by mcdurdin** [comment]
This is working on my machine -- make sure you `./build.sh stop build start` on the keymanweb.com site first?

**Comment by Meng-Heng** [comment]
> make sure you ./build.sh stop build start on the keymanweb.com site first?

Yes, I've done that. I did see a warning when ./build.sh build:
image

Some information after running docker command line?
image
I could try updating docker scout version according to the recommendation since it has been telling that whenever I run docker cmd.

**Comment by Meng-Heng** [comment]
The JSONArgsRecommended warning: https://docs.docker.com/reference/build-checks/json-args-recommended/

**Comment by mcdurdin** [comment]
OK, we may need to rubber-ducky at this point. I don't think it's likely to be a Docker issue, but I don't know for sure. We may need to park this until I am back at the office, unless @darcywong00 is able to assist remotely (I will be offline until 7 Oct).

**Comment by darcywong00** [comment]
I can try to  investigate a little. Unfortunately, my local Docker environment is similar to @Meng-Heng where it doesn't load.

**Comment by Meng-Heng** [comment]
image

**Review by mcdurdin — APPROVED** [review]

**Pull request merged**
