### PR TITLE
feat: use shared sites infrastructure

### PR DESCRIPTION
**Pull request by mcdurdin**
Note: consolidation of build.sh steps will come in a future PR. This just removes the duplicated files and uses the shared files instead.

Relates to:
* https://github.com/keymanapp/help.keyman.com/pull/817
* https://github.com/keymanapp/api.keyman.com/pull/208

### CODE REVIEW

**Comment by darcywong00** [comment]
Ah, I should probably abandon #81 since the code is now moved to shared-sites.
We may want to review some subtle differences for TIER_TEST where I was planning to use
```
$this->keymanweb_com = "http://host.docker.internal:8057"; // Unique for keymanweb.com
```

**Comment by mcdurdin** [comment]
> We may want to review some subtle differences for TIER_TEST where I was planning to use

Yes, I definitely don't want those to diverge between sites. We should probably redo the way the whole set is defined...

**Comment by darcywong00** [comment]
I think this override still needs to be in place for testing?

> $this->keymanweb_com = "http://host.docker.internal:8057";

**Comment by mcdurdin** [comment]
> I think this override still needs to be in place for testing?
> 
> > $this->keymanweb_com = "http://host.docker.internal:8057";

Tests are passing so I don't think it needs the override. That would only really be needed if we had REST calls to itself?

**Comment by darcywong00** [comment]
> Tests are passing so I don't think it needs the override

It seems TIER_TEST would then be running tests on the live keymanweb.com site instead of proposed local changes on a PR?

https://github.com/keymanapp/shared-sites/blob/c7586ec649f3766e4aece1a02b7d3aa148bf7859/_common/KeymanHosts.php#L126-L133

**Comment by darcywong00** [comment]
ah nvm, I see ci.yml is already using host.docker.internal...

**Review by darcywong00 — APPROVED** [review]
lgtm

**Pull request merged**
